### ISSUE TITLE
Afterware not compatible with apollo

### ISSUE THREAD

**Issue by conor-mac-aoidh** [vic/apollo-phoenix-websocket#1]
Just a minor issue, but I think there is a typo relating to the afterware in this repository:

https://github.com/vic/apollo-phoenix-websocket/blob/master/src/index.js#L114

This repo uses `afterUse` for the afterware, whereas the apollo client core uses `useAfter`. See:

http://dev.apollodata.com/core/network.html#networkInterfaceAfterware

**Comment by vic** [comment]
Oh good catch, thank you! will fix it, also just noticed the readme example for middleware does not wrap the object in an array (both `use` and `useAfter` take arrays of objects) will try to fix this today. Thank you

**Comment by vic** [comment]
Fixed in cc88af2f25ba0dc51b0cdc15fcd876038a648736, 7970ca3fe0bd92ed395a986ba3b6b795bc1ba30d, just released `v0.3.0`.

**Comment by conor-mac-aoidh** [comment]
Thanks! One other issue, I'm not sure if the afterware is actually being called? Middleware is invoked by the `applyWares` method here:

https://github.com/vic/apollo-phoenix-websocket/blob/master/src/index.js#L10

But afterware doesn't seem to get triggered at all.

I have been using afterware for general error catching in apollo (checking the responses from HTTP requests). Even though this uses WebSockets not HTTP, it would be nice to do something similar.

Also, `joinChannel` does not handle errors. There can be errors here if you are using authentication on joining a channel for example. I have fixed this by passing the `reject` promise to `joinChannel` like so:

```
  function joinChannel(reject) {
    if (!socket.conn.isConnected()) {
      return socket.conn.connect();
    }
    if (!chan.conn) {
      chan.conn = socket.conn.channel(channel.topic, channel.params || {});
    }
    if (!chan.conn.isJoined() && !chan.conn.isJoining()) {
      chan.conn.join()
        .receive('ok', _ => {
          const queue = chan.queue;
          chan.queue = [];
          map(performQuery, queue);
        })
        .receive('error', err => {
          chan.conn.leave();
          chan.conn = null;
          reject(new Error(err));
        });
    }
  }
```

**Comment by vic** [comment]
Hm, could you provide a PR for handling the join error ? I guess the same would be needed when connecting to the channel.  

As for the afterware, yep that's their use. I did wrote a test that expects an afterware to replace the server response, if you can create a failing test for it, please provide another PR 

Thank you for using vic's software, buggy and delicious. :D

**Comment by conor-mac-aoidh** [comment]
@vic Yes I will prepare a PR for join/connect errors shortly! Thanks!
