### ISSUE TITLE
can't set context

### ISSUE THREAD

**Issue by G3z** [vic/apollo-phoenix-websocket#22]
i tried adding a context as showed in the readme
```javascript
applyMiddleware({ request, options }, next) {
	// get the authentication token from local storage if it exists
	const store = require('libs/store').default;
	const token = store.getState().credentials && store.getState().credentials.token;
	request.context = token ? { guardian_token: token } : null;

	next();
},
```

but on phoenix this is what i get `%{"vsn" => "1.0.0"}`
```elixir
def connect(params, socket) do
    IO.inspect params
    # ...
end
```

am I doing something wrong ?

**Comment by richeterre** [comment]
I have exactly the same problem. Couldn't find the answer anywhere, maybe @vic can help?

**Comment by richeterre** [comment]
Got the answer on Slack today! You can pass the token to your `connect` params like so:

```elixir
networkInterface.use([{
  applyMiddleware({ request, options }, next) {
    const token = 'my-secret-token'
    options.params = {
      ...options.params,
      guardian_token: token,
    }

    next()
  },
}])
```

**Comment by G3z** [comment]
thanks @richeterre I tried and it's working.
@vic should I edit the [readme](https://github.com/vic/apollo-phoenix-websocket#middlewares) with this example ?

**Comment by joshuataylor** [comment]
Now that absinthe_phoenix supports context, the above snippet changing networkInterface is perfect. Maybe replace the auth bit in the readme with that?

**Comment by vic** [comment]
@joshuataylor , @G3z  yes please if you are using an updated version of absinthe_phoenix, please send a PR updating the README with a proper example. 

Thank you.

**Comment by G3z** [comment]
done https://github.com/vic/apollo-phoenix-websocket/pull/28
