### ISSUE TITLE
Absinthe?

### ISSUE THREAD

**Issue by elie222** [vic/apollo-phoenix-websocket#6]
Is this a different solution to:
https://github.com/absinthe-graphql/absinthe/issues/156
?

**Comment by vic** [comment]
@elie222 I'd say it's not a different solution. 

Absinthe is awesome, (currently using it four a couple of APIs of mine) and it's a server side technology, not really tied to any client you could use this or relay or plain curl to ask some gql.

Actually I'm using Absinthe for executing the queries, and used that as an example on the readme. I'm also interested on that issue, how to use absinthe for gql subscriptions and certainly using sockets can be a good candidate for that, so I guess I'll be looking forward to integrate subscriptions when @benwilson512 reports on what they'll look like with an Absinthe backend.

**Comment by conor-mac-aoidh** [comment]
@vic - @benwilson512 has posted [an example](https://github.com/benwilson512/phoenix_chat_example/pull/1/files) of what subscriptions look like with an Absinthe backend. We should definitely start exploring how we can add subscription support to this repo.

**Comment by vic** [comment]
@conor-mac-aoidh great! thanks for the link to the example. And yes we should start adding subscriptions

AFAIK apollo-client supports two kind of subscriptions, *real* gql subscriptions and polling-subscriptions (particular to apollo) not requiring the server to support nothing more than queries/mutations.  So I guess the second ones are already possible with this repo. But certainly we should explore looking at the linked example and support real gql subs.

As a side note, the Apollo guys are willing to accept some documentation PR for how to integrate with a Phoenix backend [see this issue](https://github.com/apollostack/core-docs/issues/238#issuecomment-272572533), some nice people have already written posts about it (see links in the issue).

**Comment by vic** [comment]
So let's close this as I guess there's nothing to do for this issue.
