### ISSUE TITLE
Add supscription support

### ISSUE THREAD

**Issue by conor-mac-aoidh** [vic/apollo-phoenix-websocket#7]
Just to continue the discussion from [this issue](https://github.com/vic/apollo-phoenix-websocket/issues/6) about adding subscription support. There is an example here of apollo/absinthe subscriptions. However, there does not seem to be much documentation on the apollo side of their subscription support.. It is not mentioned at all in the [API reference](http://dev.apollodata.com/core/apollo-client-api.html).

There is a `SubscriptionNetworkInterface` [here](https://github.com/apollostack/apollo-client/blob/master/src/transport/networkInterface.ts#L52). So I take it then that we need to add `subscribe` and `unsubscribe` methods to the network interface created by this repo?

Or should there actually be a separate network interface for subscriptions? See [this repo](https://github.com/apollostack/subscriptions-transport-ws/blob/master/src/client.ts)

**Comment by vic** [comment]
My first guess is that `subscriptions-transport-ws` is just the ws protocol part, handling the websocket connection, joining, etc (not really sure as I've not digged in the code).  In our case I guess that would correspond to `phoenix.js` (that handles the little protocol that phoenix uses to multiplex messages, the socket heartbeats, etc) not sure if I could have some time this week to look at this, but thank you very much for researching it. 

If you do have time, I'd say the first step would be to use the Absinthe example locally, and understand what is required from the client side using phoenix Sockets.  

Regarding the Apollo subscription documentation, yes, they do have documented the `watch` subscriptions (polling) but not the gql subscriptions, and looking at the networkInterface, those `subscribe` and `unsubscribe` methods are also not part of the NetworkInterface api, but we could just implement them and see how it goes. 

Thank you again :)

**Comment by conor-mac-aoidh** [comment]
@vic thanks for the feedback! Yeah, after looking at that repository a bit more I realised it was not a network interface layer for apollo.

I've setup the example locally. I will describe the results here. The example uses a channel called `__absinthe__:control`. This is the subscription message:

```json
{
	"topic": "__absinthe__:control",
	"event": "doc",
	"payload": {
		"query": "\n      subscription Messages {\n        message(room: \"lobby\") {\n          body\n          author { name }\n        }\n      }\n      ",
		"variables": {}
	},
	"ref": "2"
}
```

Response:

```json
{
	"topic": "__absinthe__:control",
	"ref": "2",
	"payload": {
		"status": "ok",
		"response": {
			"ref": "__absinthe__:14874113"
		}
	},
	"event": "phx_reply"
}
```

Then a mutation is sent:

```json
{
	"topic": "__absinthe__:control",
	"event": "doc",
	"payload": {
		"query": "\n          mutation SendMessage($body: String!, $user: String!) {\n            sendMessage(room: \"lobby\", body: $body, user: $user) {\n              __typename\n            }\n          }\n          ",
		"variables": {
			"body": "test message",
			"user": "test"
		}
	},
	"ref": "4"
}
```

Followed by a reply:

```json
{
	"topic": "__absinthe__:control",
	"ref": "4",
	"payload": {
		"status": "ok",
		"response": {
			"data": {
				"sendMessage": {
					"__typename": "Message"
				}
			}
		}
	},
	"event": "phx_reply"
}
```

And then a subscription response:

```json
{
	"topic": "__absinthe__:control",
	"ref": null,
	"payload": {
		"data": {
			"message": {
				"body": "test message",
				"author": {
					"name": "test"
				}
			}
		}
	},
	"event": "subscription:data"
}
```

**Comment by conor-mac-aoidh** [comment]
So, the only difference I am seeing is that the query must also 'subscribe' to the `subscription:data` event/room and pass any results back to the observable.

**Comment by vic** [comment]
@conor-mac-aoidh I've made a bit of refactor on the code to support subscriptions, you can see it on the `feature/subscription` branch, still have to implement tests and then try to use it with the example phoenix chat backend.
